arm_poses:
  nav_pose:
    d1: 0.5
    q1: 1.396
    q2: -1.15
    q3: -0.65
    q4: 1.5
    q5: 0.5
    q6: -1.5
  static_pose:
    d1: 0.0
    q1: 1.396
    q2: -0.506
    q3: -2.182
    q4: 0.85
    q5: 0.5
    q6: -1.5